import spacy
import re
import glob

nlp = spacy.load("en_core_web_sm")

path = "/content/big.txt"
for file in glob.glob(path):
    with open(file, encoding='utf-8', errors='ignore') as bigFile:
        text = bigFile.read()
        pattern = '[a-zA-Z]+'
        lines = re.findall(pattern,text, flags=re.IGNORECASE)
        for line in lines:
            line = nlp(line)
            for word in line:
              if spacy.explain(word.pos_)=='noun' or spacy.explain(word.pos_)=='adverb':
                  print(word,":",spacy.explain(word.pos_))

        
        
        
#   Output for first 200 lines                  
# Project : noun
# Adventures : noun
# Holmes : noun
# Sir : noun
# Doyle : noun
# Sir : noun
# Doyle : noun
# Copyright : noun
# laws : noun
# world : noun
# copyright : noun
# laws : noun
# country : noun
# Project : noun
# eBook : noun
# first : adverb
# thing : noun
# Project : noun
# file : noun
# permission : noun
# print : noun
# information : noun
# eBook : noun
# Project : noun
# file : noun
# information : noun
# rights : noun
# restrictions : noun
# file : noun
# also : adverb
# donation : noun
# Project : noun
# World : noun
# Vanilla : noun
# Texts : noun
# eBooks : noun
# Humans : noun
# Computers : noun
# eBooks : noun
# Thousands : noun
# Volunteers : noun
# Title : noun
# Adventures : noun
# Holmes : noun
# Author : noun
# Sir : noun
# Doyle : noun
# Release : noun
# Date : noun
# recently : adverb
# Edition : noun
# Language : noun
# Character : noun
# ASCII : noun
# GUTENBERG : noun
# EBOOK : noun
# Jose : noun
# ARTHUR : noun
# DOYLE : noun
# CONTENTS : noun
# Scandal : noun
# Bohemia : noun
# II : noun
# League : noun
# Case : noun
# Identity : noun
# Valley : noun
# Mystery : noun
# V : noun
# Pips : noun
# Man : noun
# Lip : noun
# Adventure : noun
# Carbuncle : noun
# Adventure : noun
# Band : noun
# Adventure : noun
# Engineer : noun
# s : noun
# Thumb : noun
# X : noun
# Adventure : noun
# Bachelor : noun
# Adventure : noun
# Beryl : noun
# Adventure : noun
# Copper : noun
# Beeches : noun
# ADVENTURE : noun
# SCANDAL : noun
# BOHEMIA : noun
# Holmes : noun
# always : adverb
# woman : noun
# seldom : adverb
# name : noun
# eyes : noun
# eclipses : noun
# sex : noun
# emotion : noun
# love : noun
# emotions : noun
# particularly : adverb
# admirably : adverb
# reasoning : noun
# machine : noun
# world : noun
# position : noun
# never : adverb
# passions : noun
# things : noun
# observer : noun
# men : noun
# s : noun
# motives : noun
# actions : noun
# reasoner : noun
# intrusions : noun
# finely : adverb
# temperament : noun
# factor : noun
# results : noun
# Grit : noun
# instrument : noun
# power : noun
# lenses : noun
# emotion : noun
# nature : noun
# yet : adverb
# there : adverb
# woman : noun
# woman : noun
# late : adverb
# memory : noun
# Holmes : noun
# lately : adverb
# marriage : noun
# away : adverb
# happiness : noun
# home : noun
# interests : noun
# around : adverb
# man : noun
# first : adverb
# establishment : noun
# attention : noun
# Holmes : noun
# form : noun
# society : noun
# soul : noun
# lodgings : noun
# Street : noun
# books : noun
# week : noun
# week : noun
# cocaine : noun
# ambition : noun
# drug : noun
# energy : noun
# nature : noun
# still : adverb
# ever : adverb
# deeply : adverb
# crime : noun
# faculties : noun
# powers : noun
# observation : noun
# clues : noun
# mysteries : noun
# official : noun
# police : noun
# time : noun
# time : noun
# account : noun
# doings : noun
# summons : noun
# Odessa : noun
# case : noun
# murder : noun
# tragedy : noun
# Atkinson : noun
# brothers : noun
# finally : adverb
# mission : noun
# so : adverb
# delicately : adverb
# successfully : adverb
# family : noun
# signs : noun
# activity : noun
# however : adverb
# merely : adverb
# readers : noun
# press : noun
# friend : noun
# companion : noun
# night : noun
# patient : noun
# now : adverb
# way : noun
# Street : noun
# door : noun
# always : adverb
# incidents : noun
# Study : noun
# Scarlet : noun
# desire : noun
# Holmes : noun
# again : adverb
# powers : noun
# rooms : noun
# brilliantly : adverb
# even : adverb
# figure : noun
# twice : adverb
# room : noun
# swiftly : adverb
# eagerly : adverb
# head : noun
# chest : noun
# hands : noun
# behind : adverb
# mood : noun
# habit : noun
# attitude : noun
# story : noun
# work : noun
# again : adverb
# drug : noun
# scent : noun
# problem : noun
# formerly : adverb
# part : noun
# seldom : adverb
# hardly : adverb
# word : noun
# kindly : adverb
# eye : noun
# armchair : noun
# case : noun
# case : noun
# gasogene : noun
# Then : adverb
# fire : noun
# fashion : noun
# Wedlock : noun
# suits : noun
# Watson : noun
# half : noun
# pounds : noun
# Indeed : adverb
# Just : adverb
# trifle : adverb
# Watson : noun
# again : adverb
# harness : noun
# Then : adverb
# very : adverb
# lately : adverb
# servant : noun
# girl : noun
# Holmes : noun
# too : adverb
# certainly : adverb
# centuries : noun
# ago : adverb
# country : noun
# home : noun
# mess : noun
# clothes : noun
# wife : noun
# notice : noun
# there : adverb
# again : adverb
# work : noun
# long : adverb
# hands : noun
# together : adverb
# simplicity : noun
# eyes : noun
# inside : adverb
# just : adverb
# firelight : noun
# strikes : noun
# leather : noun
# almost : adverb
# cuts : noun
# Obviously : adverb
# very : adverb
# carelessly : adverb
# round : adverb
# edges : noun
# order : noun
# mud : noun
# Hence : adverb
# deduction : noun
# weather : noun
# particularly : adverb
# boot : noun
# specimen : noun
# slavey : noun
# gentleman : noun
# rooms : noun
# iodoform : adverb
# mark : noun
# silver : noun
# right : adverb
# right : adverb
# side : noun
# hat : noun
# indeed : adverb
# pronounce : noun
# member : noun
# profession : noun
# ease : noun
# process : noun
# deduction : noun
# reasons : noun
# thing : noun
# always : adverb
# so : adverb
# ridiculously : adverb
# easily : adverb
# instance : noun
# reasoning : noun
# process : noun
# yet : adverb
# eyes : noun
# yours : noun
# so : adverb
# cigarette : noun
# down : adverb
# armchair : noun
# distinction : noun
# example : noun
# frequently : adverb
# steps : noun
# room : noun
# Frequently : adverb
# often : adverb
# hundreds : noun
# times : noun
# Then : adverb
# there : adverb
# so : adverb
# yet : adverb
# just : adverb
# point : noun
# Now : adverb
# there : adverb
# steps : noun
# way : noun
# problems : noun
# enough : adverb
# chronicle : noun
# experiences : noun
# sheet : noun
# notepaper : adverb
# table : noun
# either : adverb
# signature : noun
# address : noun
# There : adverb
# night : noun
# quarter : noun
# clock : noun
# gentleman : noun
# desires : noun
# very : adverb
# moment : noun
# services : noun
# houses : noun
# safely : adverb
# matters : noun
# importance : noun
# hardly : adverb
# account : noun
# quarters : noun
# then : adverb
# hour : noun
# visitor : noun
# mask : noun
# indeed : adverb
# mystery : noun
# data : noun
# yet : adverb
# capital : noun
# theorise : noun
# data : noun
# Insensibly : adverb
# theories : noun
# instead : adverb
# theories : noun
# carefully : adverb
# paper : noun
# man : noun
# presumably : adverb
# companion : noun
# s : noun
# processes : noun
# paper : noun
# half : noun
# crown : noun
# packet : noun
# peculiarly : adverb
# very : adverb
# word : noun
# Holmes : noun
# paper : noun
# so : adverb
# E : noun
# P : noun
# G : noun
# paper : noun
# Holmes : noun
# name : noun
# maker : noun
# rather : adverb
# G : noun
# Gesellschaft : noun
# Company : noun
# contraction : noun
# Co : noun
# P : noun
# course : noun
# Now : adverb
# glance : noun
# Gazetteer : noun
# down : adverb
# volume : noun
# shelves : noun
# Eglonitz : noun
# here : adverb
# country : noun
# Bohemia : noun
# far : adverb
# scene : noun
# death : noun
# glass : noun
# factories : noun
# paper : noun
# mills : noun
# eyes : noun
# cigarette : noun
# paper : noun
# Bohemia : noun
# Precisely : adverb
# man : noun
# construction : noun
# sentence : noun
# account : noun
# quarters : noun
# Frenchman : noun
# so : adverb
# verbs : noun
# only : adverb
# therefore : adverb
# paper : noun
# mask : noun
# face : noun
# here : adverb
# doubts : noun
# there : adverb
# sound : noun
# horses : noun
# hoofs : noun
# wheels : noun
# Holmes : noun
# sound : noun
# beauties : noun
# guineas : noun
# apiece : adverb
# There : adverb
# s : noun
# money : noun
# case : noun
# Watson : noun
# there : adverb
# else : adverb
# better : adverb
# Holmes : noun
# bit : noun
# Doctor : noun
# pity : noun
# client : noun
# Never : adverb
# so : adverb
# Here : adverb
# down : adverb
# armchair : noun
# Doctor : noun
# best : adverb
# attention : noun
# stairs : noun
# passage : noun
# immediately : adverb
# outside : adverb
# door : noun
# Then : adverb
# there : adverb
# tap : noun
# Holmes : noun
# man : noun
# hardly : adverb
# feet : noun
# inches : noun
# height : noun
# chest : noun
# limbs : noun
# Hercules : noun
# dress : noun
# taste : noun
# bands : noun
# sleeves : noun
# fronts : noun
# cloak : noun
# shoulders : noun
# flame : noun
# silk : noun
# neck : noun
# brooch : noun
# beryl : noun
# Boots : noun
# halfway : adverb
# calves : noun
# tops : noun
# fur : noun
# impression : noun
# opulence : noun
# appearance : noun
# hat : noun
# hand : noun
# part : noun
# face : noun
# down : adverb
# cheekbones : noun
# mask : noun
# apparently : adverb
# very : adverb
# moment : noun
# hand : noun
# still : adverb
# part : noun
# face : noun
# man : noun
# character : noun
# long : adverb
# straight : adverb
# resolution : noun
# length : noun
# obstinacy : noun
# voice : noun
# strongly : adverb
# accent : noun
# address : noun
# seat : noun
# Holmes : noun
# friend : noun
# Dr : noun
# Watson : noun
# occasionally : adverb
# enough : adverb
# cases : noun
# address : noun
# address : noun
# Von : noun
# gentleman : noun
# friend : noun
# man : noun
# discretion : noun
# importance : noun
# alone : adverb
# Holmes : noun
# wrist : noun
# back : adverb
# chair : noun
# none : noun
# gentleman : noun
# shoulders : noun
# Then : adverb
# secrecy : noun
# years : noun
# end : noun
# time : noun
# importance : noun
# too : adverb
# weight : noun
# influence : noun
# history : noun
# promise : noun
# Holmes : noun
# excuse : noun
# mask : noun
# visitor : noun
# person : noun
# employs : noun
# agent : noun
# once : adverb
# title : noun
# just : adverb
# exactly : adverb
# Holmes : noun
# dryly : adverb
# circumstances : noun
# delicacy : noun
# precaution : noun
# scandal : noun
# seriously : adverb
# compromise : noun
# families : noun
# plainly : adverb
# Ormstein : adverb
# kings : noun
# Bohemia : noun
# also : adverb
# Holmes : noun
# down : adverb
# armchair : noun
# eyes : noun
# visitor : noun
# surprise : noun
# figure : noun
# man : noun
# reasoner : noun
# agent : noun
# Holmes : noun
# slowly : adverb
# eyes : noun
# impatiently : adverb
# client : noun
# state : noun
# case : noun
# better : adverb
# advise : noun
# man : noun
# chair : noun
# down : adverb
# room : noun
# agitation : noun
# Then : adverb
# gesture : noun
# desperation : noun
# mask : noun
# face : noun
# ground : noun
# right : adverb
# King : noun
# attempt : noun
# conceal : noun
# indeed : adverb
# Holmes : noun
# Gottsreich : noun
# Ormstein : adverb
# Grand : noun
# Cassel : noun
# Felstein : noun
# King : noun
# Bohemia : noun
# visitor : noun
# down : adverb
# once : adverb
# hand : noun
# business : noun
# person : noun
# Yet : adverb
# so : adverb
# confide : noun
# agent : noun
# power : noun
# purpose : noun
# Then : adverb
# Holmes : noun
# eyes : noun
# once : adverb
# briefly : adverb
# years : noun
# ago : adverb
# acquaintance : noun
# adventuress : noun
# name : noun
# Kindly : adverb
# index : noun
# Doctor : noun
# Holmes : noun
# eyes : noun
# years : noun
# system : noun
# paragraphs : noun
# men : noun
# things : noun
# so : adverb
# name : noun
# person : noun
# once : adverb
# furnish : noun
# information : noun
# case : noun
# biography : noun
# staff : noun
# commander : noun
# sea : noun
# fishes : noun
# Holmes : noun
# year : noun
# Prima : noun
# Opera : noun
# stage : noun
# quite : adverb
# so : adverb
# person : noun
# letters : noun
# now : adverb
# letters : noun
# back : adverb
